spring:
  datasource:
    url: jdbc:h2:mem:testdb  # use in-memory DB
    driver-class-name: org.postgresql.Driver
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: none  # disable Hibernate-schema for test

  liquibase:
    enabled: false  # disable Liquibase for test