server:
  port: 8080
  shutdown: graceful
spring:
  application:
    name: spotride
  banner:
    location: banner.txt
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  datasource:
    username: root
    password: root
    url: jdbc:postgresql://postgres:5432/spotridedb?currentSchema=spotride
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
  liquibase:
    change-log: /database/liquibase/master.xml
    url: jdbc:postgresql://postgres:5432/spotridedb?currentSchema=spotride
    user: root
    password: root
    driver-class-name: org.postgresql.Driver
  lifecycle:
    timeout-per-shutdown-phase: 30s

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - liquibase
          - metrics
          - shutdown
          - prometheus
  server:
    port: 8081

springdoc:
  api-docs:
    path: /api-doc

logging:
  config: classpath:log4j2.xml